import type { Metadata } from "next";
import { Noto_Sans_JP } from 'next/font/google';
import "./globals.css";

const notoSansJP = Noto_Sans_JP({
  subsets: ['latin'],  // latin と japanese を指定可能
  weight: ['400', '500', '700'], // 必要なウェイトを指定
  variable: '--font-noto',       // CSS変数として使える
});

export const metadata: Metadata = {
  title: "shion dev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja" className={notoSansJP.variable}>
      <body>
        {children}
      </body>
    </html>
  );
}
